services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for auto-reload
      - .:/app
      # Keep persistent volumes for data
      - ./data:/app/data:rw
      - ./uploads:/app/uploads:rw
      - ./output:/app/output:rw
    environment:
      - GEMINI_API_URL=${GEMINI_API_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=8080
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG  # Add debug logging
    entrypoint: ["bash", "/app/docker-entrypoint.sh"]
    command: >
      python -m uvicorn paper_reader_tools.api.server:app 
      --host 0.0.0.0 
      --port 8080 
      --reload
    restart: unless-stopped  # Add restart policy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
  web:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      # Mount source code for auto-reload
      - .:/app
    depends_on:
      api:
        condition: service_healthy
    environment:
      - API_URL=http://api:8080
      - PYTHONPATH=/app
    restart: unless-stopped  # Add restart policy
volumes:
  data:
  uploads:
  output:
